export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const SEARCH_LIST_START = 'SEARCH_LIST_START';
export const SEARCH_LIST_SUCCESS = 'SEARCH_LIST_SUCCESS';
export const SEARCH_LIST_FAIL = 'SEARCH_LIST_FAIL';

export const FETCH_LIST_START = 'FETCH_LIST_START';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAIL = 'FETCH_LIST_FAIL';

export const FILTER_LIST_START = 'FILTER_LIST_START';
export const FILTER_LIST_SUCCESS = 'FILTER_LIST_SUCCESS';
export const FILTER_LIST_FAIL = 'FILTER_LIST_FAIL';

export const COMPARE_LIST_START = 'COMPARE_LIST_START';
export const COMPARE_LIST_SUCCESS = 'COMPARE_LIST_SUCCESS';
export const COMPARE_LIST_FAIL = 'COMPARE_LIST_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_ROUTE_SIGNAL = 'SET_ROUTE_SIGNAL';